### ISSUE TITLE
Use Python's path library

### ISSUE THREAD

**Issue by SamueleDecarli** [supermaxiste/ARPEGGIO#50]
The standard Python library has a module for dealing with paths, consider using it.
https://docs.python.org/3/library/os.path.html

https://github.com/supermaxiste/ARPEGGIO/blob/b60393c653623f458ade3fed66b1943746856ddf/Snakefile#L13-L23

**Comment by supermaxiste** [comment]
All addressed in #98 with `snakemake --lint` as a quality checker for path handling
