### ISSUE TITLE
Singularity container image error

### ISSUE THREAD

**Issue by supermaxiste** [supermaxiste/ARPEGGIO#73]
When trying to run Snakemake on Singularity I get the following error:
```
Building DAG of jobs...
CreateCondaEnvironmentException:
The 'conda' command is not available inside your singularity container image. Snakemake mounts your conda installation into singularity. Sometimes, this can fail because of shell restrictions. It has been tested to work with docker://ubuntu, but it e.g. fails with docker://bash 
```

I've tried looking for solutions without success...

**Comment by SamueleDecarli** [comment]
Could you please give more details about this? I have not been able to reproduce it on my machine.

**Comment by supermaxiste** [comment]
Tried to reproduce the error, but it looks like singularity works with no issues this time.
